// <auto-generated />
namespace SignalRGridDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLockedProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLockedProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201303012305348_AddLockedProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
